# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(680, 626)
        MainWindow.setMinimumSize(QtCore.QSize(680, 626))
        MainWindow.setMaximumSize(QtCore.QSize(680, 626))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("\n"
"background-image: url(:/buttonicon/MusicButtonIcon/background.jpg);")
        self.widget.setObjectName("widget")
        self.btnstar = QtWidgets.QPushButton(self.widget)
        self.btnstar.setGeometry(QtCore.QRect(290, 20, 45, 45))
        self.btnstar.setMinimumSize(QtCore.QSize(45, 45))
        self.btnstar.setMaximumSize(QtCore.QSize(45, 45))
        self.btnstar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttonicon/MusicButtonIcon/greenplay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnstar.setIcon(icon)
        self.btnstar.setIconSize(QtCore.QSize(45, 45))
        self.btnstar.setFlat(True)
        self.btnstar.setObjectName("btnstar")
        self.btnlast = QtWidgets.QPushButton(self.widget)
        self.btnlast.setGeometry(QtCore.QRect(160, 420, 45, 45))
        self.btnlast.setMinimumSize(QtCore.QSize(45, 45))
        self.btnlast.setMaximumSize(QtCore.QSize(45, 45))
        self.btnlast.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttonicon/MusicButtonIcon/greenlast.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnlast.setIcon(icon1)
        self.btnlast.setIconSize(QtCore.QSize(45, 45))
        self.btnlast.setFlat(True)
        self.btnlast.setObjectName("btnlast")
        self.btnnext = QtWidgets.QPushButton(self.widget)
        self.btnnext.setGeometry(QtCore.QRect(430, 140, 45, 45))
        self.btnnext.setMinimumSize(QtCore.QSize(45, 45))
        self.btnnext.setMaximumSize(QtCore.QSize(45, 45))
        self.btnnext.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttonicon/MusicButtonIcon/greennext.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnnext.setIcon(icon2)
        self.btnnext.setIconSize(QtCore.QSize(45, 45))
        self.btnnext.setFlat(True)
        self.btnnext.setObjectName("btnnext")
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        palette = QtGui.QPalette()
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.0, 135.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 0, 0, 0))
        gradient.setColorAt(0.375, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(0.423533, QtGui.QColor(251, 0, 0, 145))
        gradient.setColorAt(0.45, QtGui.QColor(247, 0, 0, 77))
        gradient.setColorAt(0.477581, QtGui.QColor(255, 0, 71, 88))
        gradient.setColorAt(0.518717, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.55, QtGui.QColor(255, 0, 0, 100))
        gradient.setColorAt(0.57754, QtGui.QColor(255, 0, 0, 130))
        gradient.setColorAt(0.625, QtGui.QColor(255, 0, 0, 69))
        gradient.setColorAt(1.0, QtGui.QColor(255, 0, 0, 69))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_3.setPalette(palette)
        self.widget_3.setStyleSheet("background-color:qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 0, 0, 0), stop:0.375 rgba(255, 0, 0, 69), stop:0.423533 rgba(251, 0, 0, 145), stop:0.45 rgba(247, 0, 0, 77), stop:0.477581 rgba(255, 0, 71, 88), stop:0.518717 rgba(255, 0, 0, 130), stop:0.55 rgba(255, 0, 0, 100), stop:0.57754 rgba(255, 0, 0, 130), stop:0.625 rgba(255, 0, 0, 69), stop:1 rgba(255, 0, 0, 69))")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.widget_3)
        self.horizontalSlider.setStyleSheet("    background: red;\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"    left: 4px; right: 4px;\n"
"border-radius: 10px;\n"
"\n"
"\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.btnvolum = QtWidgets.QPushButton(self.widget_3)
        self.btnvolum.setMinimumSize(QtCore.QSize(30, 30))
        self.btnvolum.setMaximumSize(QtCore.QSize(30, 30))
        self.btnvolum.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttonicon/MusicButtonIcon/volume-off.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnvolum.setIcon(icon3)
        self.btnvolum.setIconSize(QtCore.QSize(30, 30))
        self.btnvolum.setFlat(True)
        self.btnvolum.setObjectName("btnvolum")
        self.horizontalLayout.addWidget(self.btnvolum)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.widget_3)
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(80, 20))
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(80, 20))
        self.horizontalSlider_2.setStyleSheet("    background: red;\n"
"    position: absolute; /* absolutely position 4px from the left and right of the widget. setting margins on the widget should work too... */\n"
"border-radius: 10px;\n"
"margin: 0px;")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout.addWidget(self.horizontalSlider_2)
        self.btnclock = QtWidgets.QPushButton(self.widget_3)
        self.btnclock.setMinimumSize(QtCore.QSize(30, 30))
        self.btnclock.setMaximumSize(QtCore.QSize(30, 30))
        self.btnclock.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/buttonicon/MusicButtonIcon/history.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnclock.setIcon(icon4)
        self.btnclock.setIconSize(QtCore.QSize(30, 30))
        self.btnclock.setFlat(True)
        self.btnclock.setObjectName("btnclock")
        self.horizontalLayout.addWidget(self.btnclock)
        self.verticalLayout_2.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.01 rgba(255, 0, 0, 0), stop:1 rgba(255, 0, 0, 100))")
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionPlayList = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/buttonicon/MusicButtonIcon/Music.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayList.setIcon(icon5)
        self.actionPlayList.setObjectName("actionPlayList")
        self.actionBtnMV = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/buttonicon/MusicButtonIcon/media.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBtnMV.setIcon(icon6)
        self.actionBtnMV.setObjectName("actionBtnMV")
        self.toolBar.addAction(self.actionPlayList)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBtnMV)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionPlayList.setText(_translate("MainWindow", "PlayList"))
        self.actionPlayList.setToolTip(_translate("MainWindow", "打开播放列表"))
        self.actionBtnMV.setText(_translate("MainWindow", "BtnMV"))
        self.actionBtnMV.setToolTip(_translate("MainWindow", "打开MV列表"))

import res_rc
